[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "offline-exams"
version = "0.0.1"
dependencies = [
  "python-dotenv>=1.1.0",
  "flask>=3.1.0",
  "flask-sqlalchemy>=3.1.1",
  "flask-marshmallow>=1.3.0",
  "marshmallow-sqlalchemy>=1.4.2",
  "flask-wtf>=1.2.2",
  "flask-login>=0.6.3",
  "email_validator>=2.2.0",
  "passlib>=1.7.4",
  "argon2-cffi>=23.1.0",
  "cryptography>=44.0.2",
  "python-dateutil>=2.9.0"
]
requires-python = ">=3.12"
authors = [
  {name = "Brian Dickinson", email = "dickinsonbc@gcc.edu"},
]
description = "Flask project structure demonstration."
